version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    container_name: qa_backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/app/.env
    restart: always

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    container_name: qa_frontend
    ports:
      - "8080:8080"
    env_file:
      - ../frontend/.env
    restart: always