# Stage 1: Build
FROM node:20 AS builder

WORKDIR /app

COPY ../frontend/package.json ../frontend/package-lock.json ./
RUN npm install

COPY ../frontend .

RUN npm run build

# Stage 2: Serve
FROM node:20

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]
