# Stage 1 - Builder
FROM node:20-slim AS builder

WORKDIR /app

COPY ../frontend/package*.json ./
RUN npm install

COPY ../frontend .
RUN npm run build

# Stage 2 - Production
FROM node:20-slim

WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 8080
CMD ["serve", "-s", "dist", "-l", "8080"]
