name: Deploy Pope AI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/popeai-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/popeai-backend

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/popeai-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/popeai-frontend

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/popeai-backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/popeai-frontend
            docker compose -f pope-ai/infra/docker-compose.yml down
            docker compose -f pope-ai/infra/docker-compose.yml up -d --build